### PR TITLE
Fix indenting and improve syntax

### PR DESCRIPTION
**Pull request by jD91mZM2**
Ran an indenter and slightly improved syntax.
This place sure is a mess

### CODE REVIEW

**Comment by jD91mZM2** [comment]
Also, dude, your travis isn't properly set up

**Comment by Mnpn** [comment]
yes my travis wants rake as I told you, havent bothered

**Comment by jD91mZM2** [comment]
plsmergethx

**Review by Mnpn — APPROVED** [review]
Sure, if it breaks I can undo.

**Comment by jD91mZM2** [comment]
no you can't

plsdont

**Comment by Mnpn** [comment]
There is a "revert" button c:

**Comment by jD91mZM2** [comment]
that was a clever lie :c

**Comment by Mnpn** [comment]
:c

**Pull request merged**
